package com.supermarket.cashier.controller;


import com.supermarket.util.data.manipulation.ServerManipulation;
import javafx.fxml.FXML;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.sql.ResultSet;
import java.sql.SQLException;


public class CashierController {
//  data field: to map the data (generated by controller) to the fxml component.
    @FXML
    private TextField searchKey;
    @FXML
    private Label closeLabel;
    @FXML
    private Label tNumCol;
    @FXML
    private Label tNameCol;
    @FXML
    private Label costCol;
    @FXML
    private Label priceCol;
    @FXML
    private Label productionDateCol;
    @FXML
    private Label cashierResultArea;
    @FXML
    private TextField tNum;
    @FXML
    private TextField tName;
    @FXML
    private TextField saleNum;

//    the string buffer used for SQL query, set to 0 when starting a new query.
    private StringBuffer queryBuffer = new StringBuffer();


    @FXML
    protected void cashierSearch() throws SQLException {
        String key = searchKey.getText();
        if(key.startsWith("0")){
            String searchByNo = "Tnum";
            queryBuffer.append("SELECT * FROM thing WHERE ").append(searchByNo).append("='").append(searchKey.getText()).append("'");
            System.out.println(queryBuffer.toString());
        }else{
            String searchByName = "Tname";
            queryBuffer.append("SELECT * FROM thing WHERE ").append(searchByName).append(" LIKE '%").append(searchKey.getText()).append("%'");
            System.out.println(queryBuffer.toString());
        }
        ResultSet queryResult = ServerManipulation.execQuery(queryBuffer.toString());
        queryBuffer.setLength(0);
        while(queryResult.next()) {
            updateThingTableValue(queryResult);
            cashierResultArea.setText("查询成功");
        }
        while (!queryResult.next()){
            cashierResultArea.setText("没有相关结果");
            break;
        }
    }

    /**
     *  To update the view by filling labels with rs
     * @param rs Get the result of query
     * @throws SQLException
     */
    private void updateThingTableValue(ResultSet rs) throws SQLException {
        tNumCol.setText(rs.getString("Tnum").trim());
        tNameCol.setText(rs.getString("Tname").trim());
        costCol.setText(((String) rs.getString("cost")).trim());
        priceCol.setText(((String) rs.getString("price")).trim());
        productionDateCol.setText(((String) rs.getString("production_date")).trim());
    }

    /**
     * Generate the sale information then insert into sell table in database
     * @throws SQLException
     */
    @FXML
    protected void cashierInsert() throws SQLException {
        double saleCol = 0;
        String thingNo = tNum.getText().trim();
        String thingName = tName.getText().trim();
        String soldNum = saleNum.getText().trim();

        queryBuffer.append("SELECT * FROM thing WHERE ").append("Tnum").append("='").append(thingNo).append("'");
        ResultSet saleData = ServerManipulation.execQuery(queryBuffer.toString());

        System.out.println(saleData.toString());

        queryBuffer.setLength(0);
        while (saleData.next()) {
            String priceCol = saleData.getString("price").trim();
            System.out.println(priceCol);
            String costCol = saleData.getString("cost").trim();
            saleCol = (Double.parseDouble(priceCol) - Double.parseDouble(costCol)) * Double.parseDouble(soldNum);
        }

        if (saleCol == 0.0){
            cashierResultArea.setText("错误的商品号，无法录入。");
            queryBuffer.setLength(0);
        }else {
            queryBuffer.append("INSERT INTO sell VALUES(").append("NewID()").append(",").append("'").append(thingNo).append("',").append("'").append(thingName).append("',")
                    .append("getdate()").append(",").append("'").append(saleCol).append("')");
            System.out.println(queryBuffer.toString());
            ServerManipulation.nonRsExecQuery(queryBuffer.toString());
            cashierResultArea.setText("插入成功");
            queryBuffer.setLength(0);
        }
    }

    /**
     * Click the label, then the window will close.
     */
    @FXML
    protected void closeStage(){
        Stage stage = (Stage) closeLabel.getScene().getWindow();
        stage.close();
    }
}
